/***********************************************************/
/*                                                         */
/*  FILE        :main.c                                    */
/*  DATE        :Wed, Jun 13, 2012                         */
/*  DESCRIPTION :Main Program                              */
/*  CPU TYPE    :RX62N                                     */
/*                                                         */
/*  This file is generated by KPIT GNU Project Generator.  */
/*                                                         */
/***********************************************************/
#include 	<stdlib.h>
#include    <stdio.h>

#include	<iodefine.h>
#include 	<typedefine.h>
#include 	<r_freertos.h>
#include "RPBRX210.h"

#include "robot.h"
#include "uart.h"
#include "i2c.h"
#include "com_uart.h"
#include "odometrie.h"
#include "asserv.h"
#include "adc.h"
#include "detection.h"

/*macros ==================================================*/
/*constants ==============================================*/
/*types ===================================================*/
/*structures ==============================================*/
/*private variables =======================================*/
/*private functions =======================================*/
/*entry points ============================================*/
/*public variables ========================================*/
        /* creation des mutex */
SemaphoreHandle_t xOdo_mutex;
SemaphoreHandle_t xCmd_mutex;
SemaphoreHandle_t xComAsser_mutex;
SemaphoreHandle_t xPid_mutex;
SemaphoreHandle_t xDetec_mutex;

    /* creation des reference de tâches */
static TaskHandle_t vOdo;
static TaskHandle_t vAsserv;
static TaskHandle_t vDetection;
        /* structure de pilotage */
_s_odo cmd={0,0,0,0,0,0,0,0};


unsigned long   ulTMR0OverflowCount=0;
volatile unsigned long ulHighFrequencyTickCount = 0;

extern _s_uart uart9;
/*internal public functions ===============================*/

int main (void);
void blink(void);
void test_i2c(void);
/************************************************************
 Function Name: main
   Description: Initialize the hardware, start the tasks, start the RTOS.
     Arguments: none
  Return value: none
************************************************************/

int main(void)
{
    char *hello ="hello les touneys\r\n";
    init_uart9();
    init_adc();
    put_string(hello,&uart9);

    LED0_ON;
    LED1_OFF;
    LED2_OFF;
    /* creation des mutexs et semaphore static */
    xComAsser_mutex = xSemaphoreCreateMutex();
    xOdo_mutex= xSemaphoreCreateMutex();
    xCmd_mutex = xSemaphoreCreateMutex();
    xPid_mutex = xSemaphoreCreateMutex();
    xDetec_mutex = xSemaphoreCreateMutex();

    /* creation des taches statique */
    xTaskCreate(blink,"allumer",100,NULL,1,NULL);
    xTaskCreate(write_data_asserv,"asserv_com_read",300,\
        &uart9,1,NULL);
    xTaskCreate(odometrie,"odo",200,NULL,6,&vOdo);
    xTaskCreate(asserv,"asserv",200,NULL,5,&vAsserv);
    xTaskCreate(read_data_asserv,"asserv_com_read",300,\
        &uart9,1,NULL);
//    xTaskCreate(detection,"detection",200,NULL,3,&vDetection);
    vTaskStartScheduler();    /* RTOS_USAGE */
    while(1){}; // should not land here
    return 0;
}

/*-----------------------------------------------------------*/
/* tache de gestion */
void master(void)
{
    /*init des variables */
    enum{reset,run,action,stop}state;

    state = reset;

    for(;;)
    {
        switch(state)
        {
            case reset:
            break;
            case run:
            break;
            case action:
            break;
            case stop:
            break;
        }
        vTaskDelay(pdMS_TO_TICKS(200));
    }
}

void blink(void) {
    for(;;)
    {
        LED0=~LED0;
        vTaskDelay(pdMS_TO_TICKS(500));
    }
}

void test_i2c(void)
{
    char addr = 0x00;
    char reg = 0x01;
    start_i2c();
    for(;;)
    {
        LED0=~LED0;
//        printf("Salut Elo :) \r\n Alors elle marche la com ?\n\r");
        vTaskDelay(200);
    }
}
