/***********************************************************/
/*                                                         */
/*  FILE        :main.c                                    */
/*  DATE        :Wed, Jun 13, 2012                         */
/*  DESCRIPTION :Main Program                              */
/*  CPU TYPE    :RX62N                                     */
/*                                                         */
/*  This file is generated by KPIT GNU Project Generator.  */
/*                                                         */
/***********************************************************/
#include 	<stdlib.h>
#include    <stdio.h>

#include	<iodefine.h>
#include 	<typedefine.h>
#include 	<r_freertos.h>
#include "RPBRX210.h"

#include "uart.h"
#include "i2c.h"
#include "com_uart.h"
#include "adc.h"

/*macros ==================================================*/
/*constants ==============================================*/
/*types ===================================================*/
/*structures ==============================================*/
/*private variables =======================================*/
/*private functions =======================================*/
/*entry points ============================================*/
/*public variables ========================================*/
unsigned long   ulTMR0OverflowCount=0;
volatile unsigned long ulHighFrequencyTickCount = 0;

extern _s_uart uart9;
extern SemaphoreHandle_t xMutex_com_asser;
/*internal public functions ===============================*/

int main (void);
void blink(void);
void test_i2c(void);
/************************************************************
 Function Name: main
   Description: Initialize the hardware, start the tasks, start the RTOS.
     Arguments: none
  Return value: none
************************************************************/

int main(void)
{
    char *hello ="hello les touneys\r\n";
    init_uart9();
    init_adc();
    put_string(hello,&uart9);

    LED0_ON;
    LED1_OFF;
    LED2_OFF;
    /* creation des mutexs et semaphore static */
    xMutex_com_asser = xSemaphoreCreateMutex();
    /* creation des taches statique */
//    xTaskCreate(blink,"allumer",100,NULL,1,NULL);
    xTaskCreate(test_i2c,"allumer",100,NULL,1,NULL);
//    xTaskCreate(read_data_asserv,"asserv_com_read",300,\
        &uart9,1,NULL);
    vTaskStartScheduler();    /* RTOS_USAGE */
    while(1){}; // should not land here
    return 0;
}

/*-----------------------------------------------------------*/

void blink(void) {
    char *res_adc, *test;
    unsigned short a=121;
    for(;;) {
        LED1=~LED1;
        a = get_adc(0);
        sprintf(test,"val recu 1 : %i\r\n",a);
        put_string(test,&uart9);
        a = get_adc(2);
        sprintf(test,"val recu 2 : %i\r\n",a);
        put_string(test,&uart9);
        vTaskDelay(500);
    }
}

void test_i2c(void)
{
    char addr = 0x00;
    char reg = 0x01;
//    start_i2c();
    for(;;)
    {
        LED0=~LED0;
        printf("Salut Elo :) \r\n Alors elle marche la com ?\n\r");
        vTaskDelay(200);
    }
}
